// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA96ZnvGrbJm5KPlJVNneaL7dMraAjcFRg',
    appId: '1:203034737044:web:fa0115ce8d580773d8f781',
    messagingSenderId: '203034737044',
    projectId: 'mylibrary-omar-flutter',
    authDomain: 'mylibrary-omar-flutter.firebaseapp.com',
    storageBucket: 'mylibrary-omar-flutter.firebasestorage.app',
    measurementId: 'G-EZX2GHY68Z',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6uboHFpxLhl0UJS3b9sOhlchbbVsyuKY',
    appId: '1:203034737044:ios:d53ecdb6bdf15e12d8f781',
    messagingSenderId: '203034737044',
    projectId: 'mylibrary-omar-flutter',
    storageBucket: 'mylibrary-omar-flutter.firebasestorage.app',
    iosBundleId: 'com.example.learningFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6uboHFpxLhl0UJS3b9sOhlchbbVsyuKY',
    appId: '1:203034737044:ios:d53ecdb6bdf15e12d8f781',
    messagingSenderId: '203034737044',
    projectId: 'mylibrary-omar-flutter',
    storageBucket: 'mylibrary-omar-flutter.firebasestorage.app',
    iosBundleId: 'com.example.learningFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA96ZnvGrbJm5KPlJVNneaL7dMraAjcFRg',
    appId: '1:203034737044:web:db68159ddaf3cfecd8f781',
    messagingSenderId: '203034737044',
    projectId: 'mylibrary-omar-flutter',
    authDomain: 'mylibrary-omar-flutter.firebaseapp.com',
    storageBucket: 'mylibrary-omar-flutter.firebasestorage.app',
    measurementId: 'G-2C635XFKFN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHkJUxN_QM_5QnS_VFBJnLPqBNq6WU1Hk',
    appId: '1:203034737044:android:d0e3ec41fff0cd6ed8f781',
    messagingSenderId: '203034737044',
    projectId: 'mylibrary-omar-flutter',
    storageBucket: 'mylibrary-omar-flutter.firebasestorage.app',
  );

}